# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a basic Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the source code
COPY src/ /app/src
COPY tests/ /app/tests

# If there were dependencies, you would install them here
# RUN pip install -r requirements.txt

# Set the entry point for the container to run the agent
ENTRYPOINT ["python", "src/agent.py"]
